export const FREIND_REQUEST = "FREIND_REQUEST";
export const FREIND_ACCEPT = "FREIND_ACCEPT";
export const GENERAL_MESSAGE = "GENERAL_MESSAGE";
export const GREETING_MESSAGE = "GEETING_MESSAGE";
export const CONNECT_NOTICE = "CONNECT_NOTICE";
export const DISCONNECT_NOTICE = "DISCONNECT_NOTICE";
export const CONNECT_ANSWER = "CONNECT_ANSWER";